### ISSUE TITLE
fix: exception in toolbar in keydownhandler when focusableElements have not been determined

### ISSUE THREAD

**Issue by mollykreis** [microsoft/fast#5756]
# 🐛 Bug Report

There is a race condition in the toolbar component that can cause an exception to be thrown in the keydownhandler.

If `this.$fastController.isConnected` is `false` within `slottedItemsChanged()`, then `focusableElements` is not set within the toolbar. As a result, when trying to navigate the toolbar using arrow keys, the `keydownhandler` throws an exception because `focusableElements` is undefined when [trying to determine if preventDefault should be called](https://github.com/microsoft/fast/blob/1898cd9a73f2cf9496a2a78d18e13bd87aa012df/packages/web-components/fast-foundation/src/toolbar/toolbar.ts#L189).

## 💻 Repro or Code Sample

I'm running into problems within an Angular app where I have a toolbar containing a few buttons.
Steps to reproduce:
- click the toolbar to focus it
- press the right-arrow key on the keyboard to attempt to move focus from the first button to the second button
- see an exception rather than the focus change

## 🤔 Expected Behavior

When the right-arrow key on the keyboard is pressed, focus should move to the next button in the toolbar rather than throwing an exception.

## 😯 Current Behavior

An exception is thrown:
```
Uncaught TypeError: Cannot read properties of undefined (reading '1')
    at Toolbar.keydownHandler (toolbar.js:144:1)
    at BindingBehavior.binding (toolbar.template.js:17:21)
    at BindingBehavior.handleEvent (binding.js:246:1)
    at Toolbar.task.callback (zone.js:1596:1)
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Zone.runTask (zone.js:178:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:1)
    at invokeTask (zone.js:1600:1)
    at Toolbar.globalZoneAwareCallback (zone.js:1626:1)
```

## 💁 Possible Solution

Within fast-foundation toolbar, possibly call `this.reduceFocusableElements()` when `this.$fastController` becomes connected if `this.focusableElements` isn't defined.

## 🔦 Context

I cannot use the toolbar in my Angular app because keyboard navigation throws exceptions.

## 🌍 Your Environment

* OS & Device: Windows 10 PC
* Browser Microsoft Edge
* Version 99.0.1150.39

**Comment by mollykreis** [comment]
My original assessment of exactly what was happening to cause the exception was incorrect. I now believe that the more fundamental issue is that `reduceFocusableElements()` is called when the slotted items change, but that does not include items in the `start` or `end` slot. In my app, I don't have any items in the default slot, so the slotted items never change after the element is connected.

I'm not sure why the slotted items change to an empty array in my non-angular app but not in my angular app, but I think the correct solution is to listen for changes to the `start` and `end` slots.
