### ISSUE TITLE
fix: error when running playwright tests

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#5804]
# 🐛 Bug Report

The Playwright test steps for `@microsoft/fast-components` are failing to run.

## 💻 Repro or Code Sample

1. `yarn install`
2. `yarn workspace @microsoft/fast-components test-pw:full`

## 🤔 Expected Behavior

Playwright runs and all tests pass.

## 😯 Current Behavior

```log
yarn workspace v1.22.11
yarn run v1.22.11
$ mocha --config ./__test__/.mocharc.json ./__test__/**/*.spec.js

TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
    at new NodeError (node:internal/errors:371:5)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
    at formattedImport (/home/runner/work/fast/fast/packages/web-components/fast-components/node_modules/mocha/lib/esm-utils.js:6:23)
    at Object.exports.requireOrImport (/home/runner/work/fast/fast/packages/web-components/fast-components/node_modules/mocha/lib/esm-utils.js:23:14)
    at Object.exports.loadFilesAsync (/home/runner/work/fast/fast/packages/web-components/fast-components/node_modules/mocha/lib/esm-utils.js:33:34)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:61:5)
    at /home/runner/work/fast/fast/node_modules/esm/esm.js:1:34535
    at /home/runner/work/fast/fast/node_modules/esm/esm.js:1:34176
    at process.<anonymous> (/home/runner/work/fast/fast/node_modules/esm/esm.js:1:34506)
    at Function.<anonymous> (/home/runner/work/fast/fast/node_modules/esm/esm.js:1:296[8](https://github.com/microsoft/fast/runs/5855396287?check_suite_focus=true#step:14:8)56)
    at Function.<anonymous> (/home/runner/work/fast/fast/node_modules/esm/esm.js:1:2[9](https://github.com/microsoft/fast/runs/5855396287?check_suite_focus=true#step:14:9)6555)
    at Function.<anonymous> (/home/runner/work/fast/fast/node_modules/esm/esm.js:1:284879)
    at Object.apply (/home/runner/work/fast/fast/node_modules/esm/esm.js:1:199341)
    at node:internal/main/run_main_module:17:47
    at async singleRun (/home/runner/work/fast/fast/packages/web-components/fast-components/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/home/runner/work/fast/fast/packages/web-components/fast-components/node_modules/mocha/lib/cli/run.js:362:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /home/runner/work/fast/fast/.yarn/releases/yarn-1.22.[11](https://github.com/microsoft/fast/runs/5855396287?check_suite_focus=true#step:14:11).cjs test-pw
Directory: /home/runner/work/fast/fast/packages/web-components/fast-components
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

## 💁 Possible Solution

Replace the harness/Mocha setup with `@playwright/test` and use Storybook to host the fixtures.

## 🌍 Your Environment

This is currently failing on the "Validate Platforms/Browsers" pipeline on GH Actions.

**Comment by EisenbergEffect** [comment]
@janechu You've been looking into this area in other repos lately. Any chance you could take a look at this and propose/submit a solution?
