### ISSUE TITLE
docs: fix documentation in Integrations >> React 

### ISSUE THREAD

**Issue by squidjam** [microsoft/fast#6573]
# 🙋 Documentation Request

While following the documentation on how to use FAST with React, the app ultimately shows an error:

```
Uncaught TypeError: Reflect.getPrototypeOf called on non-object
    at Reflect.getPrototypeOf (<anonymous>)
    at Object.getAccessors (platform.js:80:1)
    at getElementKeys (index.js:57:1)
    at ReactComponent.render (index.js:169:1)
    at finishClassComponent (react-dom.development.js:19752:1)
    at updateClassComponent (react-dom.development.js:19698:1)
    at beginWork (react-dom.development.js:21611:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
```

Environment Details:
Windows 10 Enterprise Version: `10.0.19044 Build 19044`
VS Code Version: `1.74.1`
NodeJS Version: `18.12.1`
Package versions:
```    
    "@microsoft/fast-components": "^2.30.6",
    "@microsoft/fast-element": "^1.10.3",
    "@microsoft/fast-foundation": "^2.46.10",
    "@microsoft/fast-react-wrapper": "^0.3.10",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
```
Steps to reproduce:
* Install NodeJS latest LTS
* Run command `npx create-react-app my-app`
* Enter into `my-app` folder
* Run command `npm install --save @microsoft/fast-components @microsoft/fast-foundation @microsoft/fast-element @microsoft/fast-react-wrapper`
* (Optional: if you use Windows) Run command `npm install --save-dev cross-env`
* Modify package.json as instructed by documentation (Optional: if you use Windows, ad `cross-env` before `EXTEND_ESLINT=true ` on every entry for the scripts)
* Follow the rest of the documentation up to the text that reads: Congratulations! You're now set up to use FAST and React!
* Run command `npm start`

## 💁 Possible Solution

I'm not sure if this is a documentation issue or a code issue, so I don't think there's a clear possible solution.

**Comment by karan127** [comment]
Yes.. Following the steps in documentation gives the above mentioned error.

**Comment by squidjam** [comment]
Hi, in case it makes it any easier, here's a repo that reproduces the issue.
https://github.com/squidjam/fast-app-error

**Comment by apanada** [comment]
I got the same error: 

platform.js:72 
        
    Uncaught TypeError: Reflect.getPrototypeOf called on non-object
    at Reflect.getPrototypeOf (<anonymous>)
    at Object.getAccessors (platform.js:72:1)
    at getElementKeys (index.js:48:1)
    at ReactComponent.render (index.js:163:1)
    at finishClassComponent (react-dom.development.js:17151:1)
    at updateClassComponent (react-dom.development.js:17101:1)
    at beginWork (react-dom.development.js:18609:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:179:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:227:1)
    at invokeGuardedCallback (react-dom.development.js:284:1)

**Comment by lednhatkhanh** [comment]
Also happens to me

**Comment by janechu** [comment]
This will be included in our upcoming documentation update for v2 of `@microsoft/fast-element`. Please open a new issue after launch of v2 if you still see any gaps in the documentation.
