### ISSUE TITLE
"@microsoft/fast-foundation": "^2.47.1-0" makes the app not work

### ISSUE THREAD

**Issue by wxw-matt** [microsoft/fast#6666]
# 🐛 Bug Report

Got errors when I had `"@microsoft/fast-foundation": "^2.47.1-0",` in the dependencies.
```
  "dependencies": {
    "@microsoft/fast-components": "^2.17.0",
    "@microsoft/fast-element": "^1.11.0",
    "@microsoft/fast-foundation": "^2.47.1-0",
    "@microsoft/fast-react-wrapper": "^0.3.15",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
```
Errors: 
```
2platform.js:80 
        
       Uncaught TypeError: Reflect.getPrototypeOf called on non-object
    at Reflect.getPrototypeOf (<anonymous>)
    at Object.getAccessors (platform.js:80:1)
    at getElementKeys (index.js:57:1)
    at ReactComponent.render (index.js:169:1)
    at finishClassComponent (react-dom.development.js:19752:1)
    at updateClassComponent (react-dom.development.js:19698:1)
    at beginWork (react-dom.development.js:21611:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
react-dom.development.js:18687 
        
       The above error occurred in the <ReactComponent> component:

    at ReactComponent (http://localhost:3000/static/js/bundle.js:53414:9)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
react-dom.development.js:26923 
        
       Uncaught TypeError: Reflect.getPrototypeOf called on non-object
    at Reflect.getPrototypeOf (<anonymous>)
    at Object.getAccessors (platform.js:80:1)
    at getElementKeys (index.js:57:1)
    at ReactComponent.render (index.js:169:1)
    at finishClassComponent (react-dom.development.js:19752:1)
    at updateClassComponent (react-dom.development.js:19698:1)
    at beginWork (react-dom.development.js:21611:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
```

## 💻 Repro or Code Sample

Reproduction:
Just follow the steps in this tutorial:
https://www.fast.design/docs/integrations/react/

## 🤔 Expected Behavior

It should show a button with text 'Click Me'.
![image](https://user-images.githubusercontent.com/55307382/223930416-82fbd2da-3148-40e1-b50c-f6ca58041254.png)

## 😯 Current Behavior

See the errors above, and a blank page

## 🌍 Your Environment

* OS & Device: WSL/Ubuntu 20.04.3 LTS
* Browser Microsoft Edge

**Comment by squidjam** [comment]
Sadly this was reported since December last year and no one seems able to pay attention to it:
https://github.com/microsoft/fast/issues/6573

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
