### ISSUE TITLE
fix: Date Selection in FluentCalendar MAUI Blazor hybrid

### ISSUE THREAD

**Issue by guillaume-brouillon** [microsoft/fast#6766]
# 🐛 Bug Report

In Maui Blazor Hybrid, when selecting a date using FluentCalendar, the app crashes with error : 
Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at Microsoft.Fast.Components.FluentUI.FluentCalendar.OnDateSelected(CalendarSelectEventArgs args) in /_/src/Microsoft.Fast.Components.FluentUI/Components/Calendar/FluentCalendar.razor.cs:line 161
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Everything is working fine with a pure blazor project. 

## 💻 Repro or Code Sample

Create a MAUI Blazor app. Configure it to use Fluent UI. Add a FluentCalendar. 

## 🤔 Expected Behavior

Select the date

## 😯 Current Behavior

App crashes

## 🌍 Your Environment

Widows 11, Maui Blazor
* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
Please report Blazor specific issues at https://github.com /microsoft /fluentui-blazor
