### ISSUE TITLE
Fast components are not working with parcel bundler

### ISSUE THREAD

**Issue by stevebeauge** [microsoft/fast#6782]
# 🐛 Bug Report

Fast components are not working when bundled using parcel bundler.

This issue has been created after narrowing [my original issue in the Microsoft Graph Toolkit](https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/2598).

## 💻 Repro or Code Sample

Here's a minimal repo that illustrates the issue: https://github.com/stevebeauge/repro-parcel-fast/blob/main/src/index.html

## 🤔 Expected Behavior

Fast components should work using any bundler.

## 😯 Current Behavior

At runtime, the component is "blank", even if there's something in the DOM

![image](https://github.com/microsoft/fast/assets/184604/76075de9-288b-46ad-9f17-cbc5927165fd).

There's also an error in the console:

````
button.js:121  Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at Button.connectedCallback (button.js:121:32)
    at FASTElementDefinition.define (fast-definitions.js:97:22)
    at DefaultDesignSystem.register (design-system.js:181:34)
    at 8lqZg.@microsoft/fast-components (index.js:7:6)
    at newRequire (index.975ef6c8.js:71:24)
    at index.975ef6c8.js:122:5
    at index.975ef6c8.js:145:3
connectedCallback @ button.js:121
define @ fast-definitions.js:97
register @ design-system.js:181
8lqZg.@microsoft/fast-components @ index.js:7
newRequire @ index.975ef6c8.js:71
(anonymous) @ index.975ef6c8.js:122
(anonymous) @ index.975ef6c8.js:145
````

[As @gavinbarron highlighted](https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/2598#issuecomment-1636267901), there's something wrong with the exports

## 💁 Possible Solution

As a workaround, switching to the CDN version of the component make the issue disappear (repro: https://github.com/stevebeauge/repro-parcel-fast/blob/8ee6fac7307df65eacf43c32a26b32fb8aa3d2b5/src/index.html#L14-L15).

But this is not applicable in my actual project (fast is not a direct dependency)

## 🔦 Context

This issue ultimately prevents me to use Microsoft Graph Toolkit in the latest release (V3) inside a browser extension.

## 🌍 Your Environment

* OS & Device: Windows 11 x64 desktop PC
* Browser: issue tested with MS Edge
* Version: latest of every package (currently :
  ````json
  "dependencies": {
    "@microsoft/fast-components": "^2.30.6",
    "@microsoft/fast-element": "^1.12.0",
    "@microsoft/fast-foundation": "^2.49.0"
  },
  "devDependencies": {
    "parcel": "^2.9.3"
  }
  ````

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
