### ISSUE TITLE
fix: broken link in component explorer

### ISSUE THREAD

**Issue by bkardell** [microsoft/fast#7002]
# 🐛 Bug Report

Go to a component, like: https://explore.fast.design/components/fast-progress-ring

expand the menu at the top left

click any of the 'picker' items. Nothing happens. 

 Open the devtools - find the stack trace

```javascript
npm.react-dom.7f43026ea686e5aed840.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'scenarios')
    at oc.getScenarioData (main.48ab7930f3aed5ee9386.js:7855:13865)
    at Object.handleUpdateRoute [as onLocationUpdate] (main.48ab7930f3aed5ee9386.js:7855:7483)
    at handleLocationUpdate (npm.microsoft.c1e60be92bcf704d0f8f.js:1:16813)
    at Object.o (npm.react-dom.7f43026ea686e5aed840.js:2:801)
    at p (npm.react-dom.7f43026ea686e5aed840.js:2:944)
    at npm.react-dom.7f43026ea686e5aed840.js:2:1090
    at v (npm.react-dom.7f43026ea686e5aed840.js:2:1176)
    at ot (npm.react-dom.7f43026ea686e5aed840.js:2:16692)
    at it (npm.react-dom.7f43026ea686e5aed840.js:2:16502)
    ```

## 💻 Repro or Code Sample

n/a

## 🤔 Expected Behavior

Not that :) 

## 😯 Current Behavior

See above

## 🌍 Your Environment

MacOS, happened in several chromium browsers.

**Comment by janechu** [comment]
This site is no longer maintained.
